export interface Product {
  id: string
  title: string
  category: string
  price: number
  originalPrice: number
  image: string
  rating: number
  reviews: number
  badge?: string
  description: string
  images: string[]
  sizes: string[]
  colors: string[]
  gender?: 'mens' | 'womens' | 'unisex'
}

const PRODUCTS: Product[] = [
  // ── MEN'S ──────────────────────────────────────────────────────────
  {
    id: '1',
    title: 'Mens Winter Leather Jacket',
    category: 'Jacket',
    price: 48.0,
    originalPrice: 75.0,
    image: '/assets/images/products/jacket-1.jpg',
    rating: 4,
    reviews: 8,
    badge: '15%',
    description:
      'Premium quality winter leather jacket crafted with genuine leather. Features a warm interior lining, multiple utility pockets, and a classic fit suitable for all outdoor occasions.',
    images: [
      '/assets/images/products/jacket-1.jpg',
      '/assets/images/products/jacket-2.jpg',
      '/assets/images/products/jacket-3.jpg',
      '/assets/images/products/jacket-4.jpg',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['#1A1A2E', '#4A3728', '#2C5F2E'],
    gender: 'mens',
  },
  {
    id: '2',
    title: 'Pure Garment Dyed Cotton Shirt',
    category: 'Shirt',
    price: 45.0,
    originalPrice: 56.0,
    image: '/assets/images/products/shirt-1.jpg',
    rating: 3,
    reviews: 5,
    badge: 'Sale',
    description:
      'Crisp, lightweight casual shirt made from 100% pure garment-dyed cotton. Breathable fabric that gets softer with every wash. Tailored for a smart-casual summer look.',
    images: [
      '/assets/images/products/shirt-1.jpg',
      '/assets/images/products/shirt-2.jpg',
      '/assets/images/products/jacket-1.jpg',
      '/assets/images/products/jacket-2.jpg',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['#FFFFFF', '#3B82F6', '#EF4444', '#10B981'],
    gender: 'mens',
  },
  {
    id: '3',
    title: 'MEN Yarn Fleece Full-Zip Jacket',
    category: 'Jacket',
    price: 58.0,
    originalPrice: 65.0,
    image: '/assets/images/products/jacket-2.jpg',
    rating: 3,
    reviews: 12,
    description:
      'Cozy yarn-dyed fleece jacket featuring a full-zip front, mock collar, and zip hand pockets. Provides excellent warmth-to-weight ratio for cool weather layering.',
    images: [
      '/assets/images/products/jacket-2.jpg',
      '/assets/images/products/jacket-1.jpg',
      '/assets/images/products/jacket-3.jpg',
      '/assets/images/products/jacket-4.jpg',
    ],
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['#4B5563', '#1F2937', '#1E3A8A'],
    gender: 'mens',
  },
  {
    id: '4',
    title: 'Brown Casual Bomber Jacket',
    category: 'Jacket',
    price: 78.0,
    originalPrice: 110.0,
    image: '/assets/images/products/jacket-3.jpg',
    rating: 4,
    reviews: 11,
    description:
      'Classic bomber jacket featuring ribbed collar, cuffs, and hem. Sturdy zip closure and lightweight insulated fill make this an excellent windbreaker for transition seasons.',
    images: [
      '/assets/images/products/jacket-3.jpg',
      '/assets/images/products/jacket-1.jpg',
      '/assets/images/products/jacket-2.jpg',
      '/assets/images/products/jacket-4.jpg',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['#78350F', '#1F2937', '#065F46'],
    gender: 'mens',
  },
  {
    id: '5',
    title: 'Men Slim Fit Formal Jacket',
    category: 'Jacket',
    price: 120.0,
    originalPrice: 160.0,
    image: '/assets/images/products/jacket-4.jpg',
    rating: 4,
    reviews: 7,
    description:
      'Expertly tailored slim-fit formal blazer jacket. Structured shoulders, notched lapels, and double back vents for a modern sharp corporate profile.',
    images: [
      '/assets/images/products/jacket-4.jpg',
      '/assets/images/products/jacket-1.jpg',
      '/assets/images/products/jacket-2.jpg',
      '/assets/images/products/jacket-3.jpg',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['#1E2937', '#0F172A', '#334155'],
    gender: 'mens',
  },
  {
    id: '6',
    title: 'Men Canvas Weekend Bag',
    category: 'Bags',
    price: 56.0,
    originalPrice: 74.0,
    image: '/assets/images/products/jacket-5.jpg',
    rating: 4,
    reviews: 9,
    description:
      'Durable canvas carry-all with padded straps and a roomy interior for travel, work, and weekend essentials.',
    images: [
      '/assets/images/products/jacket-5.jpg',
      '/assets/images/products/jacket-6.jpg',
    ],
    sizes: ['One Size'],
    colors: ['#A16207', '#0F172A'],
    gender: 'mens',
  },
  {
    id: '7',
    title: 'Men Casual Jacket - Olive',
    category: 'Jacket',
    price: 65.0,
    originalPrice: 85.0,
    image: '/assets/images/products/jacket-6.jpg',
    rating: 4,
    reviews: 6,
    description:
      'Lightweight casual jacket with a relaxed fit and clean minimalist design. A versatile wardrobe staple for everyday layering.',
    images: [
      '/assets/images/products/jacket-6.jpg',
      '/assets/images/products/jacket-5.jpg',
      '/assets/images/products/jacket-3.jpg',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['#4B5563', '#78350F'],
    gender: 'mens',
  },
  {
    id: '8',
    title: "Men's Hoodies T-Shirt",
    category: 'Shirt',
    price: 7.0,
    originalPrice: 17.0,
    image: '/assets/images/products/2.jpg',
    rating: 4,
    reviews: 14,
    description:
      'Casual short-sleeve hooded t-shirt made of soft, stretch cotton blend. Features raw edge details, adjustable drawstrings, and a kangaroo pouch pocket.',
    images: [
      '/assets/images/products/2.jpg',
      '/assets/images/products/1.jpg',
      '/assets/images/products/3.jpg',
      '/assets/images/products/4.jpg',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['#374151', '#9CA3AF', '#DC2626'],
    gender: 'mens',
  },
  {
    id: '9',
    title: "Casual Men's Brown Shoes",
    category: 'Shoes',
    price: 99.0,
    originalPrice: 105.0,
    image: '/assets/images/products/shoe-1.jpg',
    rating: 5,
    reviews: 18,
    description:
      'Classic lace-up shoes built with rich synthetic leather upper and a cushioned orthotic insole. Designed for all-day walking comfort and versatile smart-casual style.',
    images: [
      '/assets/images/products/shoe-1.jpg',
      '/assets/images/products/shoe-2.jpg',
      '/assets/images/products/shoe-3.jpg',
      '/assets/images/products/shoe-4.jpg',
    ],
    sizes: ['8', '9', '10', '11', '12'],
    colors: ['#78350F', '#451A03', '#1A1A2E'],
    gender: 'mens',
  },
  {
    id: '10',
    title: 'Running & Trekking Shoes - White',
    category: 'Shoes',
    price: 49.0,
    originalPrice: 65.0,
    image: '/assets/images/products/sports-1.jpg',
    rating: 5,
    reviews: 24,
    description:
      'Performance athletic shoes engineered with mesh panels for airflow and a shock-absorbing lightweight foam midsole. Perfect for daily jogging or heavy gym workouts.',
    images: [
      '/assets/images/products/sports-1.jpg',
      '/assets/images/products/sports-2.jpg',
      '/assets/images/products/sports-3.jpg',
      '/assets/images/products/sports-4.jpg',
    ],
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['#FFFFFF', '#3B82F6', '#000000'],
    gender: 'mens',
  },
  {
    id: '11',
    title: 'Trekking Running Shoes Black',
    category: 'Shoes',
    price: 78.0,
    originalPrice: 95.0,
    image: '/assets/images/products/sports-2.jpg',
    rating: 4,
    reviews: 16,
    description:
      'All-terrain outdoor trekking and trail running shoes featuring deep-lug rubber outsoles for maximum traction on muddy or wet hiking paths.',
    images: [
      '/assets/images/products/sports-2.jpg',
      '/assets/images/products/sports-1.jpg',
      '/assets/images/products/sports-3.jpg',
      '/assets/images/products/sports-4.jpg',
    ],
    sizes: ['8', '9', '10', '11'],
    colors: ['#000000', '#4B5563', '#F59E0B'],
    gender: 'mens',
  },
  {
    id: '12',
    title: 'Sports Running Shoes - Grey',
    category: 'Shoes',
    price: 68.0,
    originalPrice: 88.0,
    image: '/assets/images/products/sports-3.jpg',
    rating: 4,
    reviews: 10,
    description:
      'Ergonomic sports shoes with a breathable upper and durable rubber outsole. Built for high-performance training sessions.',
    images: [
      '/assets/images/products/sports-3.jpg',
      '/assets/images/products/sports-4.jpg',
      '/assets/images/products/sports-5.jpg',
      '/assets/images/products/sports-6.jpg',
    ],
    sizes: ['8', '9', '10', '11'],
    colors: ['#9CA3AF', '#1F2937'],
    gender: 'mens',
  },
  {
    id: '13',
    title: 'Athletic Trainer - Blue',
    category: 'Shoes',
    price: 72.0,
    originalPrice: 90.0,
    image: '/assets/images/products/sports-4.jpg',
    rating: 4,
    reviews: 8,
    description:
      'Lightweight athletic trainers with a cushioned insole and flexible outsole, ideal for gym sessions and casual sports.',
    images: [
      '/assets/images/products/sports-4.jpg',
      '/assets/images/products/sports-5.jpg',
      '/assets/images/products/sports-6.jpg',
      '/assets/images/products/sports-1.jpg',
    ],
    sizes: ['8', '9', '10', '11'],
    colors: ['#1E40AF', '#000000'],
    gender: 'mens',
  },
  {
    id: '14',
    title: 'Trail Shoes - Orange Grip',
    category: 'Shoes',
    price: 85.0,
    originalPrice: 110.0,
    image: '/assets/images/products/sports-5.jpg',
    rating: 5,
    reviews: 13,
    badge: 'New',
    description:
      'Aggressive grip trail shoes with a protective toe cap and water-resistant upper for off-road adventures.',
    images: [
      '/assets/images/products/sports-5.jpg',
      '/assets/images/products/sports-6.jpg',
      '/assets/images/products/sports-1.jpg',
    ],
    sizes: ['8', '9', '10', '11'],
    colors: ['#F97316', '#1F2937'],
    gender: 'mens',
  },
  {
    id: '15',
    title: 'Performance Cross Trainer',
    category: 'Shoes',
    price: 92.0,
    originalPrice: 120.0,
    image: '/assets/images/products/sports-6.jpg',
    rating: 4,
    reviews: 11,
    description:
      'Versatile cross training shoe with multi-directional grip and ample cushioning for diverse workout routines.',
    images: [
      '/assets/images/products/sports-6.jpg',
      '/assets/images/products/sports-5.jpg',
      '/assets/images/products/sports-3.jpg',
    ],
    sizes: ['8', '9', '10', '11', '12'],
    colors: ['#111827', '#3B82F6'],
    gender: 'mens',
  },
  {
    id: '16',
    title: 'Classic Leather Belt',
    category: 'Accessories',
    price: 24.0,
    originalPrice: 35.0,
    image: '/assets/images/products/belt.jpg',
    rating: 4,
    reviews: 10,
    badge: 'New',
    description:
      'A polished leather belt with a brushed buckle finish and durable stitching, designed to add structure to any everyday outfit.',
    images: [
      '/assets/images/products/belt.jpg',
      '/assets/images/products/jacket-1.jpg',
    ],
    sizes: ['S', 'M', 'L'],
    colors: ['#4B5563', '#78350F'],
    gender: 'mens',
  },
  {
    id: '17',
    title: 'Smart Watch Vital Plus',
    category: 'Watches',
    price: 100.0,
    originalPrice: 120.0,
    image: '/assets/images/products/watch-1.jpg',
    rating: 4,
    reviews: 14,
    description:
      'Modern smartwatch with real-time heart rate tracking, oxygen saturation monitor, sleep tracking, and customizable digital watch faces. Connects seamlessly via Bluetooth.',
    images: [
      '/assets/images/products/watch-1.jpg',
      '/assets/images/products/watch-2.jpg',
      '/assets/images/products/watch-3.jpg',
      '/assets/images/products/watch-4.jpg',
    ],
    sizes: ['One Size'],
    colors: ['#000000', '#D1D5DB', '#DC2626'],
    gender: 'mens',
  },
  {
    id: '18',
    title: 'Pocket Watch Leather Pouch',
    category: 'Watches',
    price: 150.0,
    originalPrice: 170.0,
    image: '/assets/images/products/watch-2.jpg',
    rating: 3,
    reviews: 6,
    badge: 'Sale',
    description:
      'Vintage pocket watch with mechanical hand-wind movement, housed in a premium hand-stitched protective leather pouch with belt loop.',
    images: [
      '/assets/images/products/watch-2.jpg',
      '/assets/images/products/watch-1.jpg',
      '/assets/images/products/watch-3.jpg',
      '/assets/images/products/watch-4.jpg',
    ],
    sizes: ['One Size'],
    colors: ['#D97706', '#1E2937'],
    gender: 'mens',
  },
  {
    id: '19',
    title: 'Woolen Hat For Men',
    category: 'Accessories',
    price: 15.0,
    originalPrice: 25.0,
    image: '/assets/images/products/4.jpg',
    rating: 3,
    reviews: 15,
    description:
      'Classic ribbed knit beanie hat made of warm wool-acrylic blend yarn. Features a fold-over cuff for adjustable head coverage and wind protection.',
    images: [
      '/assets/images/products/4.jpg',
      '/assets/images/products/1.jpg',
      '/assets/images/products/2.jpg',
      '/assets/images/products/3.jpg',
    ],
    sizes: ['One Size'],
    colors: ['#1F2937', '#78350F', '#047857'],
    gender: 'mens',
  },
  {
    id: '20',
    title: 'Bleu de Chanel Eau de Parfum',
    category: 'Perfume',
    price: 120.0,
    originalPrice: 150.0,
    image: '/assets/images/products/Bleu de Chanel Eau de Parfum.jpeg',
    rating: 5,
    reviews: 42,
    badge: 'Best Seller',
    description:
      'A powerful, fresh, and clean fragrance inspired by the free-spirited man. Bleu de Chanel opens with a burst of citrus, evolving into a warm, woody base of sandalwood and cedar.',
    images: [
      '/assets/images/products/Bleu de Chanel Eau de Parfum.jpeg',
    ],
    sizes: ['50ml', '100ml', '150ml'],
    colors: ['#1E3A5F'],
    gender: 'mens',
  },

  // ── WOMEN'S ────────────────────────────────────────────────────────
  {
    id: '21',
    title: 'Black Floral Wrap Midi Skirt',
    category: 'Skirt',
    price: 25.0,
    originalPrice: 35.0,
    image: '/assets/images/products/clothes-4.jpg',
    rating: 5,
    reviews: 20,
    badge: 'New',
    description:
      'Elegant flowy midi skirt featuring an adjustable wrap waist and an all-over floral print. Perfect styling piece for weekend brunches or summer outings.',
    images: [
      '/assets/images/products/clothes-4.jpg',
      '/assets/images/products/clothes-3.jpg',
      '/assets/images/products/clothes-2.jpg',
      '/assets/images/products/clothes-1.jpg',
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['#000000', '#F43F5E', '#14B8A6'],
    gender: 'womens',
  },
  {
    id: '22',
    title: 'Velvet Evening Dress',
    category: 'Clothes',
    price: 64.0,
    originalPrice: 85.0,
    image: '/assets/images/products/clothes-3.jpg',
    rating: 5,
    reviews: 16,
    description:
      'A graceful velvet dress with a fitted waist and flowing silhouette crafted for evening events and special occasions.',
    images: [
      '/assets/images/products/clothes-3.jpg',
      '/assets/images/products/clothes-4.jpg',
    ],
    sizes: ['S', 'M', 'L'],
    colors: ['#7C3AED', '#DB2777'],
    gender: 'womens',
  },
  {
    id: '23',
    title: 'Women Denim Shorts',
    category: 'Clothes',
    price: 29.0,
    originalPrice: 39.0,
    image: '/assets/images/products/shorts-1.jpg',
    rating: 4,
    reviews: 8,
    description:
      'High-rise denim shorts with a relaxed cut and subtle stretch, ideal for summer walks, brunches, and weekend travel.',
    images: [
      '/assets/images/products/shorts-1.jpg',
      '/assets/images/products/shorts-2.jpg',
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['#1F2937', '#C084FC'],
    gender: 'womens',
  },
  {
    id: '24',
    title: 'Women Denim Shorts - Light Wash',
    category: 'Clothes',
    price: 32.0,
    originalPrice: 42.0,
    image: '/assets/images/products/shorts-2.jpg',
    rating: 4,
    reviews: 6,
    description:
      'Light-wash denim shorts with a flattering cut and vintage-inspired fade, perfect for casual summer outfits.',
    images: [
      '/assets/images/products/shorts-2.jpg',
      '/assets/images/products/shorts-1.jpg',
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['#93C5FD', '#D1FAE5'],
    gender: 'womens',
  },
  {
    id: '25',
    title: 'Womens Party Wear Shoes',
    category: 'Shoes',
    price: 25.0,
    originalPrice: 30.0,
    image: '/assets/images/products/party-wear-1.jpg',
    rating: 3,
    reviews: 9,
    badge: 'Sale',
    description:
      'Stunning slip-on pumps with a glossy finish and comfortable block heels. Ideal styling partner for evening dinners, weddings, and special events.',
    images: [
      '/assets/images/products/party-wear-1.jpg',
      '/assets/images/products/party-wear-2.jpg',
      '/assets/images/products/shoe-2.jpg',
    ],
    sizes: ['6', '7', '8', '9'],
    colors: ['#E11D48', '#EC4899', '#000000', '#F59E0B'],
    gender: 'womens',
  },
  {
    id: '26',
    title: 'High Heel Party Wear Sandals',
    category: 'Shoes',
    price: 55.0,
    originalPrice: 80.0,
    image: '/assets/images/products/shoe-2.jpg',
    rating: 3,
    reviews: 5,
    badge: 'Sale',
    description:
      'Premium elegant stiletto heel sandals with wrap-around ankle straps and soft faux leather insoles. Adds immediate sophistication to party and cocktail dresses.',
    images: [
      '/assets/images/products/shoe-2.jpg',
      '/assets/images/products/shoe-1.jpg',
      '/assets/images/products/party-wear-1.jpg',
      '/assets/images/products/party-wear-2.jpg',
    ],
    sizes: ['6', '7', '8', '9'],
    colors: ['#000000', '#F3F4F6', '#EC4899'],
    gender: 'womens',
  },
  {
    id: '28',
    title: 'Women Block Heel Boots',
    category: 'Shoes',
    price: 72.0,
    originalPrice: 95.0,
    image: '/assets/images/products/shoe-4.jpg',
    rating: 4,
    reviews: 7,
    description:
      'Sturdy block heel boots with a side zip and cushioned footbed, combining style with everyday comfort.',
    images: [
      '/assets/images/products/shoe-4.jpg',
      '/assets/images/products/shoe-3.jpg',
      '/assets/images/products/shoe-5.jpg',
    ],
    sizes: ['6', '7', '8', '9'],
    colors: ['#292524', '#78350F'],
    gender: 'womens',
  },
  {
    id: '30',
    title: 'Women Lace Bra Set',
    category: 'Lingerie',
    price: 25.0,
    originalPrice: 35.0,
    image: '/assets/images/products/clothes-2.jpg',
    rating: 4,
    reviews: 12,
    description:
      'Soft lace bra set with adjustable straps and matching briefs, designed for comfort and everyday confidence.',
    images: [
      '/assets/images/products/clothes-2.jpg',
    ],
    sizes: ['S', 'M', 'L'],
    colors: ['#F472B6', '#FFFFFF'],
    gender: 'womens',
  },
  {
    id: '31',
    title: 'Women Cotton Sleep Shirt',
    category: 'Nightwear',
    price: 22.0,
    originalPrice: 30.0,
    image: '/assets/images/products/party-wear-2.jpg',
    rating: 4,
    reviews: 10,
    description:
      'Comfortable cotton sleep shirt with soft fabric and relaxed fit, perfect for lounging and restful sleep.',
    images: [
      '/assets/images/products/party-wear-2.jpg',
    ],
    sizes: ['S', 'M', 'L'],
    colors: ['#EDE9FE', '#F9A8D4'],
    gender: 'womens',
  },
  {
    id: '32',
    title: 'Hydrating Shampoo Care',
    category: 'Cosmetics',
    price: 18.0,
    originalPrice: 24.0,
    image: '/assets/images/products/shampoo.jpg',
    rating: 4,
    reviews: 13,
    description:
      'Gentle daily shampoo infused with botanical extracts that cleanse, soften, and refresh hair for a healthy shine.',
    images: [
      '/assets/images/products/shampoo.jpg',
    ],
    sizes: ['250ml', '500ml'],
    colors: ['#FDE68A', '#BFDBFE'],
    gender: 'womens',
  },
  {
    id: '33',
    title: 'Girls T-Shirt',
    category: 'Shirt',
    price: 3.0,
    originalPrice: 5.0,
    image: '/assets/images/products/3.jpg',
    rating: 4,
    reviews: 11,
    description:
      'Cute everyday crewneck t-shirt for girls, made with breathable combed cotton fabric. Featuring screen-printed graphics that resist fading.',
    images: [
      '/assets/images/products/3.jpg',
      '/assets/images/products/1.jpg',
      '/assets/images/products/2.jpg',
      '/assets/images/products/4.jpg',
    ],
    sizes: ['4T', '5T', '6T', '8T'],
    colors: ['#F472B6', '#60A5FA', '#FBBF24'],
    gender: 'womens',
  },
  {
    id: '34',
    title: 'Belted Waist Spanish Sleeve Blouse',
    category: 'Shirt',
    price: 38.0,
    originalPrice: 52.0,
    image: '/assets/images/products/Belted Waist Spanish Sleeve Poplin Shirt Blouse.jpeg',
    rating: 4,
    reviews: 18,
    badge: 'New',
    description:
      'Elegant poplin blouse with billowing Spanish sleeves and a structured belted waist. A statement piece for effortless feminine style.',
    images: [
      '/assets/images/products/Belted Waist Spanish Sleeve Poplin Shirt Blouse.jpeg',
      '/assets/images/products/Mella Blouse Semi Vest Set.jpeg',
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['#FFFFFF', '#FEF9C3'],
    gender: 'womens',
  },
  {
    id: '35',
    title: 'Mella Blouse Semi Vest Set',
    category: 'Clothes',
    price: 55.0,
    originalPrice: 72.0,
    image: '/assets/images/products/Mella Blouse Semi Vest Set.jpeg',
    rating: 5,
    reviews: 22,
    badge: 'Trending',
    description:
      'Chic coordinated blouse and semi-vest set with a contemporary cut. Effortlessly transitions from day to evening wear.',
    images: [
      '/assets/images/products/Mella Blouse Semi Vest Set.jpeg',
      '/assets/images/products/Belted Waist Spanish Sleeve Poplin Shirt Blouse.jpeg',
      '/assets/images/products/Peter Pan collar peplum shirt..jpeg',
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['#E0F2FE', '#FDF2F8'],
    gender: 'womens',
  },
  {
    id: '36',
    title: 'Peter Pan Collar Peplum Shirt',
    category: 'Shirt',
    price: 42.0,
    originalPrice: 58.0,
    image: '/assets/images/products/Peter Pan collar peplum shirt..jpeg',
    rating: 4,
    reviews: 15,
    description:
      'A darling peplum shirt with a soft Peter Pan collar and a flattering flared hem — sweet vintage charm meets modern tailoring.',
    images: [
      '/assets/images/products/Peter Pan collar peplum shirt..jpeg',
      '/assets/images/products/Belted Waist Spanish Sleeve Poplin Shirt Blouse.jpeg',
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['#FFFFFF', '#F0FDF4'],
    gender: 'womens',
  },
  {
    id: '37',
    title: 'The Fairytale Cottage Gingham Dress',
    category: 'Clothes',
    price: 68.0,
    originalPrice: 90.0,
    image: '/assets/images/products/The Fairytale Cottage Gingham Dress.jpeg',
    rating: 5,
    reviews: 30,
    badge: 'Best Seller',
    description:
      'A whimsical gingham dress with a sweetheart neckline and tiered skirt — the ultimate cottage-core statement piece for weekend adventures.',
    images: [
      '/assets/images/products/The Fairytale Cottage Gingham Dress.jpeg',
      '/assets/images/products/Mella Blouse Semi Vest Set.jpeg',
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['#FCA5A5', '#FFFFFF', '#86EFAC'],
    gender: 'womens',
  },
  {
    id: '38',
    title: 'Miss Dior Blooming Bouquet',
    category: 'Perfume',
    price: 98.0,
    originalPrice: 130.0,
    image: '/assets/images/products/Miss Dior Blooming Bouquet Eau de Toilette.jpeg',
    rating: 5,
    reviews: 55,
    badge: 'Best Seller',
    description:
      'A delicate floral bouquet that awakens the senses. Fresh peony and white musks weave together in a light, joyful fragrance that lingers beautifully.',
    images: [
      '/assets/images/products/Miss Dior Blooming Bouquet Eau de Toilette.jpeg',
    ],
    sizes: ['30ml', '50ml', '100ml'],
    colors: ['#FBCFE8'],
    gender: 'womens',
  },
  {
    id: '39',
    title: 'YSL Libre Eau de Parfum Intense',
    category: 'Perfume',
    price: 115.0,
    originalPrice: 145.0,
    image: '/assets/images/products/Yves Saint Laurent Libre Eau de Parfum Intense..jpeg',
    rating: 5,
    reviews: 38,
    badge: 'New',
    description:
      'An intense floral-musky fragrance for the bold woman. Notes of lavender blossom and orange blossom over a warm, sensual base of vanilla and cedar.',
    images: [
      '/assets/images/products/Yves Saint Laurent Libre Eau de Parfum Intense..jpeg',
    ],
    sizes: ['30ml', '50ml', '90ml'],
    colors: ['#1C1917'],
    gender: 'womens',
  },
  {
    id: '40',
    title: 'Baby Fabric Shoes',
    category: 'Shoes',
    price: 4.0,
    originalPrice: 5.0,
    image: '/assets/images/products/1.jpg',
    rating: 5,
    reviews: 20,
    description:
      'Ultra-soft fabric baby slippers with elastic ankle bands for easy wear. Soft flannel interiors keep little feet warm and protected during crawling or first steps.',
    images: [
      '/assets/images/products/1.jpg',
      '/assets/images/products/2.jpg',
      '/assets/images/products/3.jpg',
      '/assets/images/products/4.jpg',
    ],
    sizes: ['0-6m', '6-12m', '12-18m'],
    colors: ['#FEE2E2', '#DBEAFE', '#FEF3C7'],
    gender: 'womens',
  },

  // ── JEWELRY ────────────────────────────────────────────────────────
  {
    id: '41',
    title: 'Rose Gold Earrings Set',
    category: 'Jewelry',
    price: 25.0,
    originalPrice: 45.0,
    image: '/assets/images/products/jewellery-1.jpg',
    rating: 5,
    reviews: 10,
    badge: 'Sale',
    description:
      'Dainty and charming set of hoops and studs crafted in hypoallergenic rose gold plated alloy. Adorned with tiny sparkling crystal accents.',
    images: [
      '/assets/images/products/jewellery-1.jpg',
      '/assets/images/products/jewellery-2.jpg',
      '/assets/images/products/jewellery-3.jpg',
    ],
    sizes: ['One Size'],
    colors: ['#FCA5A5', '#F59E0B', '#E5E7EB'],
  },
  {
    id: '42',
    title: 'Sterling Silver Bracelet',
    category: 'Jewelry',
    price: 38.0,
    originalPrice: 55.0,
    image: '/assets/images/products/jewellery-2.jpg',
    rating: 4,
    reviews: 8,
    description:
      'Elegant chain link bracelet made of authentic 925 sterling silver. Features a high-polish finish and an adjustable lobster claw clasp.',
    images: [
      '/assets/images/products/jewellery-2.jpg',
      '/assets/images/products/jewellery-1.jpg',
      '/assets/images/products/jewellery-3.jpg',
    ],
    sizes: ['Adjustable'],
    colors: ['#E5E7EB', '#FBBF24'],
  },
  {
    id: '43',
    title: 'Rose Quartz Necklace',
    category: 'Jewelry',
    price: 35.0,
    originalPrice: 48.0,
    image: '/assets/images/products/jewellery-3.jpg',
    rating: 5,
    reviews: 12,
    description:
      'Thoughtfully designed rose quartz pendant necklace that adds a soft, elevated finish to everyday styling.',
    images: [
      '/assets/images/products/jewellery-3.jpg',
      '/assets/images/products/jewellery-1.jpg',
    ],
    sizes: ['One Size'],
    colors: ['#F9A8D4', '#E5E7EB'],
    gender: 'womens',
  },
  {
    id: '44',
    title: 'Aurora Pearl Pendant Necklace',
    category: 'Jewelry',
    price: 62.0,
    originalPrice: 85.0,
    image: '/assets/images/products/Aurora Pearl Pendant Necklace.jpeg',
    rating: 5,
    reviews: 27,
    badge: 'New',
    description:
      'Lustrous freshwater pearl pendant suspended on a delicate gold vermeil chain. A timeless piece that elevates any look with understated elegance.',
    images: [
      '/assets/images/products/Aurora Pearl Pendant Necklace.jpeg',
      '/assets/images/products/jewellery-3.jpg',
      '/assets/images/products/jewellery-1.jpg',
    ],
    sizes: ['One Size'],
    colors: ['#F0F9FF', '#FEF3C7'],
    gender: 'womens',
  },
  {
    id: '45',
    title: 'Pearl Wreath Stud Earrings',
    category: 'Jewelry',
    price: 29.0,
    originalPrice: 42.0,
    image: '/assets/images/products/Pearl Wreath Stud Earrings.jpeg',
    rating: 5,
    reviews: 19,
    badge: 'Trending',
    description:
      'Charming floral wreath stud earrings adorned with tiny freshwater pearls. Lightweight and hypoallergenic, perfect for sensitive ears.',
    images: [
      '/assets/images/products/Pearl Wreath Stud Earrings.jpeg',
      '/assets/images/products/Aurora Pearl Pendant Necklace.jpeg',
      '/assets/images/products/jewellery-1.jpg',
    ],
    sizes: ['One Size'],
    colors: ['#F0F9FF', '#FDE68A'],
    gender: 'womens',
  },

  // ── PERFUME ────────────────────────────────────────────────────────
  {
    id: '46',
    title: 'Luxury Eau de Parfum 100ml',
    category: 'Perfume',
    price: 75.0,
    originalPrice: 110.0,
    image: '/assets/images/products/perfume.jpg',
    rating: 5,
    reviews: 32,
    description:
      'A sophisticated fragrance featuring top notes of fresh bergamot and jasmine, settling into warm amber, cedarwood, and white musk. Housed in a polished display crystal bottle.',
    images: [
      '/assets/images/products/perfume.jpg',
    ],
    sizes: ['100ml'],
    colors: ['#F59E0B'],
    gender: 'unisex',
  },
  {
    id: '47',
    title: 'Chanel No. 5 Eau Première',
    category: 'Perfume',
    price: 135.0,
    originalPrice: 165.0,
    image: '/assets/images/products/Chanel No 5 Eau Premièr.jpeg',
    rating: 5,
    reviews: 74,
    badge: 'Iconic',
    description:
      'The legendary Chanel No. 5 reimagined in a lighter, airier formulation. A brilliant, feminine scent woven from ylang-ylang, jasmine, and white musk.',
    images: [
      '/assets/images/products/Chanel No 5 Eau Premièr.jpeg',
      '/assets/images/products/Bleu de Chanel Eau de Parfum.jpeg',
    ],
    sizes: ['35ml', '75ml', '150ml'],
    colors: ['#FEF9C3'],
    gender: 'womens',
  },
]

export function getAllProducts(): Product[] {
  return PRODUCTS
}

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id)
}

export function getRelatedProducts(category: string, excludeId: string): Product[] {
  return PRODUCTS.filter(
    (p) => p.category.toLowerCase() === category.toLowerCase() && p.id !== excludeId
  ).slice(0, 4)
}
